Create repositories and services
AnnaGo21/CookingHelper pull request #4
Opened 2023-06-20 08:54 UTC by AnnaGo21

2023-06-21 09:02 UTC, giorobota requested changes
Good job, left some comments, also, I'd suggest running application after implementing each repository/entity to make sure code compiles, so you can easily find the problem.

2023-06-21 09:02 UTC, giorobota commented on src/main/java/com/example/demo/entity/IngredientsRecipes.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
recipeID should not be auto generated, it should be assigned on creation

2023-06-21 09:02 UTC, giorobota commented on src/main/java/com/example/demo/entity/Recipe.java
> +    @ManyToMany
Please specify mappings, otherwise it will not compile

2023-06-21 09:02 UTC, giorobota commented on src/main/java/com/example/demo/entity/Recipe.java
> +    private User createdBy;
No need to use mapping each time, sometimes just id or username might be enough, then you can query for user later if you need. You can review all mappings and decide for yourself

2023-06-21 09:02 UTC, giorobota commented on src/main/java/com/example/demo/entity/Ingredient.java
> +    private String measurementUnit; //ml or gr
I'd suggest making it enum wuth annotation `@Enumerated(EnumType.STRING)`, it will not require sql changes.
https://www.baeldung.com/jpa-persisting-enums-in-jpa

2023-06-27 10:53 UTC, closed without merging

2023-06-27 10:54 UTC, AnnaGo21 commented
Closed pull request